[package]
name = "elm_rs_generator"
version = "0.1.0"
edition = "2021"

[dependencies]
elm_rs = "0.2"
proto-rust = { path = ".." }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
