
[package]
name = "decoration-test"
version = "0.1.0"
edition = "2021"

[dependencies]
elm_rs = "0.2"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
buildamp-macro = { path = "../../.buildamp/macros" }
utoipa = { version = "4.2", features = ["preserve_order", "preserve_path_order"] }
chrono = { version = "0.4", features = ["serde"] }
wasm-bindgen = "0.2"
inventory = "0.3"
