[package]
name = "generate-elm-codecs"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "generate-elm-codecs"
path = "src/main.rs"

[dependencies]
elm_rs = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"